name: L10n Update
on:
  workflow_call:

jobs:
  trigger-update:
    name: L10n Update Trigger
    runs-on: ubuntu-latest

    steps:
      - name: Repository dispatch
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # v4.0.1
        with:
          token: ${{ secrets.ICINGABOT_TOKEN }}
          repository: Icinga/L10n
          event-type: update
          client-payload: '{"origin": "${{ github.repository }}", "commit": "${{ github.sha }}"}'
