on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        type: string
        default: .

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      phar: ${{ steps.phar.outputs.phar }}
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: '1'
          repository: Icinga/github-actions
          ref: php-workflow
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup PHP
        uses: shivammathur/setup-php@bf6b4fbd49ca58e4608c9c89fba0b8d90bd2a39f # v2.35.5
        with:
          php-version: 8.4

      - name: Install Dependencies
        run: composer install --no-progress --prefer-dist # --no-dev

      - name: Build PHAR
        working-directory: ${{ inputs.working-directory }}
        id: phar
        run: |
          php -d phar.readonly=0 vendor/bin/phar-composer build
          echo "::set-output name=phar::$(pwd)/phpstan-adjust-scandirs.phar"
